'------------------------------------------------------------------------------
' <auto-generated>
'     이 코드는 도구를 사용하여 생성되었습니다.
'     런타임 버전:4.0.30319.239
'
'     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
'     이러한 변경 내용이 손실됩니다.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="SibalChk2011")>  _
Partial Public Class TempShopAccountDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "확장성 메서드 정의"
  Partial Private Sub OnCreated()
  End Sub
  Partial Private Sub InsertTempShopAccount(instance As TempShopAccount)
    End Sub
  Partial Private Sub UpdateTempShopAccount(instance As TempShopAccount)
    End Sub
  Partial Private Sub DeleteTempShopAccount(instance As TempShopAccount)
    End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.System.Configuration.ConfigurationManager.ConnectionStrings("SibalChk2011ConnectionString1").ConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property TempShopAccount() As System.Data.Linq.Table(Of TempShopAccount)
		Get
			Return Me.GetTable(Of TempShopAccount)
		End Get
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="Shop.TempShopAccount")>  _
Partial Public Class TempShopAccount
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _ShopAccountID As Integer
	
	Private _ShopID As String
	
	Private _MenuName As String
	
	Private _Date As Date
	
	Private _TableNumber As Integer
	
	Private _MenuAccount As Integer
	
	Private _OrderState As System.Nullable(Of Integer)
	
    #Region "확장성 메서드 정의"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnShopAccountIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnShopAccountIDChanged()
    End Sub
    Partial Private Sub OnShopIDChanging(value As String)
    End Sub
    Partial Private Sub OnShopIDChanged()
    End Sub
    Partial Private Sub OnMenuNameChanging(value As String)
    End Sub
    Partial Private Sub OnMenuNameChanged()
    End Sub
    Partial Private Sub OnDateChanging(value As Date)
    End Sub
    Partial Private Sub OnDateChanged()
    End Sub
    Partial Private Sub OnTableNumberChanging(value As Integer)
    End Sub
    Partial Private Sub OnTableNumberChanged()
    End Sub
    Partial Private Sub OnMenuAccountChanging(value As Integer)
    End Sub
    Partial Private Sub OnMenuAccountChanged()
    End Sub
    Partial Private Sub OnOrderStateChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnOrderStateChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ShopAccountID", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property ShopAccountID() As Integer
		Get
			Return Me._ShopAccountID
		End Get
		Set
			If ((Me._ShopAccountID = value)  _
						= false) Then
				Me.OnShopAccountIDChanging(value)
				Me.SendPropertyChanging
				Me._ShopAccountID = value
				Me.SendPropertyChanged("ShopAccountID")
				Me.OnShopAccountIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ShopID", DbType:="VarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property ShopID() As String
		Get
			Return Me._ShopID
		End Get
		Set
			If (String.Equals(Me._ShopID, value) = false) Then
				Me.OnShopIDChanging(value)
				Me.SendPropertyChanging
				Me._ShopID = value
				Me.SendPropertyChanged("ShopID")
				Me.OnShopIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_MenuName", DbType:="VarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property MenuName() As String
		Get
			Return Me._MenuName
		End Get
		Set
			If (String.Equals(Me._MenuName, value) = false) Then
				Me.OnMenuNameChanging(value)
				Me.SendPropertyChanging
				Me._MenuName = value
				Me.SendPropertyChanged("MenuName")
				Me.OnMenuNameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Name:="Date", Storage:="_Date", DbType:="DateTime NOT NULL")>  _
	Public Property [Date]() As Date
		Get
			Return Me._Date
		End Get
		Set
			If ((Me._Date = value)  _
						= false) Then
				Me.OnDateChanging(value)
				Me.SendPropertyChanging
				Me._Date = value
				Me.SendPropertyChanged("[Date]")
				Me.OnDateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TableNumber", DbType:="Int NOT NULL")>  _
	Public Property TableNumber() As Integer
		Get
			Return Me._TableNumber
		End Get
		Set
			If ((Me._TableNumber = value)  _
						= false) Then
				Me.OnTableNumberChanging(value)
				Me.SendPropertyChanging
				Me._TableNumber = value
				Me.SendPropertyChanged("TableNumber")
				Me.OnTableNumberChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_MenuAccount", DbType:="Int NOT NULL")>  _
	Public Property MenuAccount() As Integer
		Get
			Return Me._MenuAccount
		End Get
		Set
			If ((Me._MenuAccount = value)  _
						= false) Then
				Me.OnMenuAccountChanging(value)
				Me.SendPropertyChanging
				Me._MenuAccount = value
				Me.SendPropertyChanged("MenuAccount")
				Me.OnMenuAccountChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_OrderState", DbType:="Int")>  _
	Public Property OrderState() As System.Nullable(Of Integer)
		Get
			Return Me._OrderState
		End Get
		Set
			If (Me._OrderState.Equals(value) = false) Then
				Me.OnOrderStateChanging(value)
				Me.SendPropertyChanging
				Me._OrderState = value
				Me.SendPropertyChanged("OrderState")
				Me.OnOrderStateChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class
