<?xml version="1.0" encoding="utf-8"?><Database Name="SibalChk2011" Class="TempShopAccountDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=124.198.16.87;Initial Catalog=SibalChk2011;Persist Security Info=True;User ID=jung" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="SibalChk2011ConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="Shop.TempShopAccount" Member="TempShopAccount">
    <Type Name="TempShopAccount">
      <Column Name="ShopAccountID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ShopID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MenuName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="TableNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MenuAccount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OrderState" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>